main: de.knabbiii.spawnelytra.SpawnElytra
version: 2.2
api-version: 1.20
author: Knabbiii
name: SpawnElytra
description: "Enable elytra-like flight mechanics at spawn without requiring elytra wings. Double-jump to fly and boost with F key! Built with Java 21 for optimal performance."
website: https://github.com/Knabbiii/SpawnElytra
softdepend: []

commands:
  spawnelytra:
    description: Main SpawnElytra command
    aliases: [se, selytra]
    usage: /<command> [reload|info]

permissions:
  spawnelytra.use:
    description: Allows players to use elytra flight at spawn
    default: true
  spawnelytra.useboost:
    description: Allows players to use boost functionality
    default: true
  spawnelytra.admin:
    description: Allows access to admin commands like reload
    default: op
  spawnelytra.*:
    description: Gives access to all SpawnElytra permissions
    default: op
    children:
      spawnelytra.use: true
      spawnelytra.useboost: true
      spawnelytra.admin: true